project/api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('bill/', views.BillList.as_view(), name="bill-list"),
    path('legislator/', views.LegislatorList.as_view(), name="legislator-list"),
    path('vote/', views.VoteList.as_view(), name="vote-list"),
    path('voteresult/', views.VoteResultList.as_view(), name="voteresult-list"),
    # path('bill/<int:pk>/', views.BillUpdate.as_view(), name="bill-update-delete"),
]

project/authentication/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("logout/", views.logout, name="logout"),
]

project/portal/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name=""),
    path("bills/", views.bills, name="bills"),
    path("legislators/", views.legislators, name="legislators"),
    path("upload/", views.upload, name="upload"),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("project.portal.urls", "portal"), namespace="portal")),
    path("api/", include("project.api.urls")),
    path("auth/", include(("project.authentication.urls", "authentication"), namespace="auth")),
]

project/portal/models.py
from django.db import models


class Legislator(models.Model):
    name = models.CharField(max_length=80, unique=True, null=True)

    @property
    def supported_bills(self):
        return VoteResult.objects.filter(legislator_id=self.pk, vote_type=1).count() or "-"

    @property
    def opposed_bills(self):
        return VoteResult.objects.filter(legislator_id=self.pk, vote_type=2).count() or "-"

    def __str__(self):
        return self.name or "-"


class Bill(models.Model):
    title = models.CharField(max_length=80, unique=True, null=True)
    sponsor_id = models.ForeignKey(
        to=Legislator, 
        verbose_name="Primary sponsor", 
        on_delete=models.PROTECT
    )

    @property
    def supporters(self):
        return VoteResult.objects.filter(vote_id__bill_id=self.pk, vote_type=1).count() or "-"

    @property
    def opposers(self):
        return VoteResult.objects.filter(vote_id__bill_id=self.pk, vote_type=2).count() or "-"

    @property
    def primary_sponsor(self):
        return self.sponsor_id

    def __str__(self):
        return self.title


class Vote(models.Model):
    bill_id = models.ForeignKey(Bill, null=True, on_delete=models.PROTECT)


class VoteResult(models.Model):
    legislator_id = models.ForeignKey(Legislator, on_delete=models.PROTECT)
    vote_id = models.ForeignKey(Vote, on_delete=models.PROTECT)
    vote_type = models.IntegerField(choices=[(1, "Yea"), (2, "Nay")])

project/authentication/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email"]

project/portal/forms.py
from django import forms
from django.core.validators import FileExtensionValidator


class UploadFile(forms.Form):
    file = forms.FileField(
        label="",
        validators=[FileExtensionValidator(allowed_extensions=["csv"])],
        widget=forms.ClearableFileInput(attrs={"class": "form-control w-25 ms-auto me-auto mb-3"}),
    )

project/api/views.py
from rest_framework.generics import ListCreateAPIView

from project.portal import models

from . import serializers


class BillList(ListCreateAPIView):
    queryset = models.Bill.objects.all()
    serializer_class = serializers.BillSerializer

class LegislatorList(ListCreateAPIView):
    queryset = models.Legislator.objects.all()
    serializer_class = serializers.LegislatorSerializer

class VoteList(ListCreateAPIView):
    queryset = models.Vote.objects.all()
    serializer_class = serializers.VoteSerializer

class VoteResultList(ListCreateAPIView):
    queryset = models.VoteResult.objects.all()
    serializer_class = serializers.VoteResultSerializer

# class BillUpdate(RetrieveUpdateDestroyAPIView):
#     queryset = models.Bill.objects.all()
#     serializer_class = BillSerializer
#     lookup_field = 'pk'

project/authentication/views.py
from django.contrib import auth
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import redirect, render

from .forms import RegisterForm


def login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = auth.authenticate(request, username=username, password=password)

        if user:
            auth.login(request, user)
            return redirect("portal:")
    form = AuthenticationForm()
    return render(request, "login.html", {"form": form})


def register(request):
    form = RegisterForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect("auth:login")
    return render(request, "register.html", {"form": form})


def logout(request):
    auth.logout(request)
    return redirect("auth:login")

project/portal/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render

from .forms import UploadFile
from .handlers import handle_input_file
from .models import Bill, Legislator
from .tables import BillDetailTable, LegislatorDetailTable, get_table_for


@login_required
def home(request):
    return render(request, "home.html")


@login_required
def bills(request):
    values = Bill.objects.all()
    table = BillDetailTable(values)
    return render(request, "bills.html", {"table": table})


@login_required
def legislators(request):
    values = Legislator.objects.all()
    table = LegislatorDetailTable(values)
    return render(request, "legislators.html", {"table": table})


@login_required
@user_passes_test(lambda u: u.is_superuser, login_url="/")
def upload(request):
    form = UploadFile(request.POST, request.FILES)
    if form.is_valid():
        uploaded_content = form.cleaned_data["file"]
        success, model, imported_data = handle_input_file(uploaded_content.file)

        if success:
            table = get_table_for(model, imported_data)
            return render(request, "upload.html", {"imported_data": table})
    return render(request, "upload.html", {"form": UploadFile()})

project/authentication/templates/login.html
{% extends "base.html" %}

{% block title %} Login {% endblock %}

{% block content %}
<div class="text-center border border-light rounded-3  p-5 w-25 mx-auto">
  <form method="post">
    {% csrf_token %}
    <div class="mb-4">
      {{ form.username.label }}
      {{ form.username }}
    </div>
    <div class="mb-4">
      {{ form.password.label }}
      {{ form.password }}
    </div>
    <div>
      <button type="submit" class="btn btn-light mb-2">Sign in</button>
    </div>
    <a href="{% url 'auth:register' %}" class="h6 mb-2">Register</a>
  </form>
</div>
{% endblock %}

project/authentication/templates/register.html
{% extends "base.html" %}

{% block title %} Register {% endblock %}

{% block content %}
<div class="text-center border border-light rounded-3  p-5 w-25 mx-auto">
  <form method="post">
    {% csrf_token %}
    <div class="mb-4">
      {{ form.username.label }}
      {{ form.username }}
    </div>
    <div class="mb-4">
      {{ form.email.label }}
      {{ form.email }}
    </div>
    <div class="mb-4">
      {{ form.password1.label }}
      {{ form.password1 }}
    </div>
    <div class="mb-4">
      {{ form.password2.label }}
      {{ form.password2 }}
    </div>
    <div>
      <button type="submit" class="btn btn-light mb-2">Register</button>
    </div>
    <a href="{% url 'auth:login' %}" class="h6 mb-2">Sign in</a>
  </form>
</div>
{% endblock %}

project/portal/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Home
      {% endblock %}
    </title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.3/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.datatables.net/v/bs5/dt-2.0.6/b-3.0.2/b-colvis-3.0.2/b-html5-3.0.2/b-print-3.0.2/cr-2.0.1/r-3.0.2/datatables.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'assets/file-earmark-text-fill.svg' %}"/>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-dark-subtle">
        <div class="container py-1">
            <a class="navbar-brand">Q</a>
            {% if request.user.is_authenticated %}
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'portal:' %}">Home</a>
                    </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'portal:bills' %}">Bills</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'portal:legislators' %}">Legislators</a>
                  </li>
                  {% if request.user.is_superuser %}
                    <li class="nav-item"> 
                      <a class="nav-link" href="{% url 'portal:upload' %}">Upload Data</a>
                    </li>
                  {% endif %}
                </ul>
                <ul class="navbar-nav ms-auto me-5 ">
                    <li class="nav-item dropdown">
                        <button class="bg-transparent border-0 nav-link" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-person-circle"></i>
                        </button>
                        <ul class="dropdown-menu" style="min-width: 50%;" aria-labelledby="navbarDropdown">
                          <li><a class="dropdown-item" href="{% url 'auth:logout' %}">Sign out</a></li>
                        </ul>
                    </li>
                </ul>
              </div>
            {% endif %}
        </div>
    </nav>
    <div class="container mt-5">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/v/bs5/dt-2.0.6/b-3.0.2/b-colvis-3.0.2/b-html5-3.0.2/b-print-3.0.2/cr-2.0.1/r-3.0.2/datatables.min.js"></script>
  </body>
</html>

project/portal/templates/bills.html
{% extends "base.html" %}

{% load render_table from django_tables2 %}

{% load static %}

{% block title %} Bills {% endblock %}

{% block content %}
<div class="text-center">
    {% if table.data %}
        <h4 class="mb-2">Bills supporters and opposers count</h4>
        <div class="mb-4 border p-4 border-black-subtle rounded-3">
            {% render_table table %}
        </div>
    {% else %}
        <h4>No records found.</h4>
    {% endif %}
</div>
<script src="{% static 'js/tabledefs.js' %}"></script>
{% endblock %}

project/portal/templates/home.html
{% extends "base.html" %}

{% block title %} Home {% endblock %}

{% block content %}
<div class="ms-auto text-center ">
    <h4>Welcome! You can visualize and export legislative data navigating to <a href="{% url 'portal:bills' %}">bills</a> or to <a href="{% url 'portal:legislators' %}">legislators</a>.</h4>
</div>
{% endblock %}

project/portal/templates/legislators.html
{% extends "base.html" %}

{% block title %} Legislators {% endblock %}

{% load render_table from django_tables2 %}

{% load static %}

{% block content %}
<div class="text-center">
    {% if table.data %}
        <h4 class="mb-2">Legislators supported and opposed bills</h4>
        <div class="mb-4 border p-4 border-black-subtle rounded-3">
            {% render_table table %}
        </div>
    {% else %}
        <h4>No records found.</h4>
    {% endif %}
</div>
<script src="{% static 'js/tabledefs.js' %}"></script>
{% endblock %}

project/portal/templates/upload.html
{% extends "base.html" %}

{% load render_table from django_tables2 %}

{% block title %} Upload Data {% endblock %}

{% block content %}
<div class="text-center ms-auto">
    <div class="mt-3">
        {% if form %}
            <h4 class="mb-4">Import data by uploading CSV file</h4>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn btn-light border-1 border-dark-subtle w-25">Submit</button>
            </form>
        {% else %}
            <h4 class="mb-2">Success! Imported data:</h4>
            <div class="mb-4 text-center border p-4 border-black-subtle rounded-3">
                {% render_table imported_data %}
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}